### ISSUE TITLE
[ATK] Analog Joystick Test

### ISSUE THREAD

**Issue by SukkoPera** [keirf/Amiga-Stuff#20]
In ATK, it would be nice to be able to test analog joysticks too. This would make sure that the rough ADCs in Paula work correctly.

And/or an actual analog joystics, of course :).

**Comment by SukkoPera** [comment]
Hey man, you rock! Very well done! Just one note: it would be useful to keep track of the min/max values reached on the X/Y axes.

**Comment by keirf** [comment]
Good idea. One thing to note is that the values can wrap beyond 255 if the RC charge delay in the joystick is too high. I found this after modding a PC joystick with an extra 100nF on each pot. This is because PC sticks use a lower pot resistance than Amiga sticks. It worked fine on one axis but so happened my x axis will wrap to (256+)23 ish.

Now in a game I would deal with that wrap and also if course allow the full range of the joystick to be calibrated. But in the test I prefer just to deal in raw values, bit probably makes sense to detect and report the wrap in the min/max values?

**Comment by keirf** [comment]
One thing to note is that this is at 50hz whereas the pots are designed not to overflow if the counters are read with 16.6ms of setup (ie ntsc 60hz). Something for me to think about. I think the wrap is still useful to report at pal frequency. Maybe.

**Comment by SukkoPera** [comment]
I guess what you should do depends on what old games did: did PAL games cope with the possible overflow, or can they be fooled by it? In the latter case I think it would be better to detect and report the overflow to the user.

Since adding caps to extend the X/Y range seems to be a popular mod (it is actually sort of why I'm asking), reporting overflows can also be useful to help people test different cap values until the best one is found.

**Comment by keirf** [comment]
Any thoughts on #35? I don't think there's much confusion in the test?

**Comment by keirf** [comment]
Here's a new firmware to try. It reports min/max and can report pot values up to nearly 500. If you're close to that value it means you don't have a pot connected on that line! Give it a try please:

[atk_20_1.zip](https://github.com/keirf/Amiga-Stuff/files/5318179/atk_20_1.zip)

**Comment by SukkoPera** [comment]
Will do tonight.

About #35, sorry but it took me quite a bit to come up with a meaningful reply :).

**Comment by keirf** [comment]
That's okay, and it's resulted in a change :) Here's the new latest build:

[atk_20_2.zip](https://github.com/keirf/Amiga-Stuff/files/5318369/atk_20_2.zip)

**Comment by SukkoPera** [comment]
Everything tests good here :).
