### ISSUE TITLE
RAM test can pass even when memory is incorrectly configured

### ISSUE THREAD

**Issue by davepoo** [keirf/Amiga-Stuff#22]
In an Amiga 4000 repair video (Adrians Digital Basement). He installed some 1Mb memory which was incorrectly configured to via a jumper to act as 4Mb memory.
The memory test however still passed as it seems the memory test was seeing the misconfigured RAM addresses as mirrors of the working RAM.
I feel like the random fill test could be setup differently to detect this situation. It seems like the random fill patern is too repetetive to catch this error.
So in his case a 16Mb ram test passed, when only 4Mb was actually in the computer.

Issue is described here from https://youtu.be/mJkiblw8Wl8?t=867 to 16:30

**Comment by keirf** [comment]
I'll check it out, the repeat length shouldn't be a power of two and so shouldn't suffer this problem. If I'm wrong I can probably force it so or find another pseudo random sequence.

**Comment by keirf** [comment]
I did some investigation. The random fill pattern is a 32-bit sequence of length 2^32-1. That is, it can actually fill 16GB (less four bytes) of memory without repeating a 32-bit word. I also manually checked memory contents after fill, in UAE, and found that there was no repetition at obvious power-of-two boundaries.

If someone who can actually reproduce this issue wants to investigate it with me, then I'm happy to do so. Otherwise I can find no issue here to fix.

**Comment by keirf** [comment]
I'll close for now. Anyone who sees this kind of issue is welcome to reopen or raise a new ticket.

**Comment by davepoo** [comment]
Thanks for the investigation, i'll was pretty sure that was going to be the issue. I'm now left wondering how the ram test managed to pass.

**Comment by keirf** [comment]
It should be impossible unless those SIMMs are 4M each after all. Or maybe there's a more subtle bug in ATK. Hence why this would need to be dived into more deeply.
