### ISSUE TITLE
paddles

### ISSUE THREAD

**Issue by mnx-xx** [keirf/Amiga-Stuff#35]
I know, this is quite rare device, but with atari paddles connected, it says "paddles not detected". But analog joystick test works with them, so maybe name this test analog+paddles?

**Comment by keirf** [comment]
That's 'pad not detected' (cd32 gamepad), not paddles.

I called the test Analog to try to encompass paddles too. But let's be honest noone has ever seriously used paddles on the Amiga.

I did wonder about giving linear representations of X and Y instead of an XY plot. But I think the latter is nicer for joystick and quite usable for paddles too.

**Comment by mnx-xx** [comment]
Ok, thank you for explanation. Yes its true, I know only one simple game, which use them. Keep the work on this fantastic utility, which helped me a lot ;)

**Comment by SukkoPera** [comment]
I've always thought that an explicit mention of "CD32" in the test title would make things more clear. This is because "gamepad" is a pretty generic term: the Sega Master System and Megadrive also had their own gamepads, which happen to be somewhat compatible with Amigas too, so some confusion may arise.

Something else to consider is that some people, especially non-English-speaking, might not differentiate between a "joystick" and a "gamepad". I know some older people here in Italy that call every controller a "joystick". If the test title explicitly pointed to the CD32, I'm sure they would at least understand that it is targeted at that specific "joystick".

"Analog" sounds fine to me, but maybe "Analog/Paddles" would be clearer. Not all people might know how paddles work internally.

Quick digression: I think keirf is assuming that ATK will mainly get used by people with specific knowledge of the machine and peripherals, that's why some terms might be confusing to beginners. But some tests are more immediate than others and can be used even by people without a background, so maybe the terminology could be improved for these. The controller test is probably the easiest one to pick up and many people might use it to test controllers rather than the machine.

About the XY plot vs. linear representation, I think the former is more universal, even though I'm not sure what happens to the missing dimension: I guess the absolute value doesn't mind, but it ought to be somewhat stable at least.

**Comment by keirf** [comment]
@SukkoPera Regarding linear representation I would simply show each pot value on its own horizontal axis.

I will look at names of the controller types. They have to be kept somewhat short is all. I suppose 'CD32 Pad' might be a good idea.
