### ISSUE TITLE
Checkerboard Pattern for Video Calibration on OSSC

### ISSUE THREAD

**Issue by CharlieBeatnik** [keirf/Amiga-Stuff#37]
Hi Keir,

Firstly, the Amiga Test Kit is absolutely fabulous and recently helped me diagnose an issue with one of my CIA chips, so thank you! 

I was wondering if you would consider adding a black & white checkerboard pattern to the Video section of Amiga Test Kit?

I appreciate you probably don't want that menu to turn into a full video calibration system, but a checkerboard pattern (ideally with the option to alternate it on each frame) would be extremely useful for finding the optimal horizontal sample rate and sampling phase with video scalers such as the OSSC. 

You can see a video of a checkerboard pattern being used to dial in pixel perfect calibration settings here - https://youtu.be/dEr3uFPs7gU?t=155

Happy to answer any questions about this request, I think it would be a really useful feature.

Many thanks,
Andy.

**Comment by keirf** [comment]
So you want hi-res (640x200 or x256) pixels alternating black/white horizontally and vertically? That makes sense. What's the extra benefit of alternating each pixel every frame (50/60Hz)?

**Comment by keirf** [comment]
Does this do what you need? Is the alternating version actually useful?

[atk_37_1.zip](https://github.com/keirf/Amiga-Stuff/files/5595553/atk_37_1.zip)

**Comment by CharlieBeatnik** [comment]
Standard 256 lines is fine (or I guess 200 for NTSC?). The reason you want the option to alternate is that it lets you dial in the final few degrees of sampling phase, you can see something similar to a moire effect when they alternate if the sampling phase isn't crack on. This video demonstrates it - https://youtu.be/1HkBblIhuXw?t=1248

Thank you for such a quick turnaround on this. I'll test that build at lunchtime!

**Comment by CharlieBeatnik** [comment]
So this is absolutely great! The alternating works really well. If I could ask for a couple of tweaks if possible:

- The checkerboard squares are not square, they need to be double the width. 
![Rectangles](https://user-images.githubusercontent.com/27673984/100227588-426c1700-2f19-11eb-846d-23558ec82f83.jpg)

- If possible, could you move the keyboard shortcuts menu up a little so at least a few rows of the checkerboard can be seen at the bottom of the screen. This is great for configuring screen extents on the OSSC. Alternatively a dedicated screen extents menu option in the Video section would also be great. 

Many thanks again for this, it's awesome!

**Comment by keirf** [comment]
The pixels are hi-res non-interlaced which are unfortunately not square. We would either need to interlace (probably flickery on an OSSC with no buffering), or do lo-res pixels (or double up the hi-res pixels). Is it actually better to have the double-width pixels: I would have thought you get more desirable calibration precision with more, thinner pixels? After all it is the horizontal resolution that largely matters I would have thought?

Regarding screen extents, that is actually supported on the "Colour gradients" screen. The white outlines are exactly Amiga NTSC and Amiga PAL sized. So you can just drop into that test card for configuring screen extents. Is that okay? Because actually the checkerboard is on a smaller-even-than-NTSC screen size. So it is definitely not good for extents configuration.

**Comment by CharlieBeatnik** [comment]
Got you, so that's 640x200, hence why the pixels aren't square. That makes sense and I agree it's probably the right thing to do for calibration as it's rising and falling between black and white for each pixel. Intuitively I thought it was wrong but I think you're right to keep it like that.

And that's great info about the "Colour gradients" screen showing the extents, I hadn't realised that.

All in all the change looks good, thank you again Keir!
