### ISSUE TITLE
[LOW priority] Zip file has commit ID instead of version number when building with Docker

### ISSUE THREAD

**Issue by rjnorthrow** [keirf/Amiga-Stuff#49]
When building with Docker, since v-1.17, the zip output file has the Git commit ID instead of the version number and it's the same when specifying `-e COMMIT=testkit-v1.18`:

```
docker run -ti --rm -v$(pwd):/output rjnorthrow/atk:latest
```

Expected output: `AmigaTestKit-v1.18.zip`, actual output: `AmigaTestKit-803ec6a.zip`

Up to v1.16, the zip file was named as expected

**Comment by keirf** [comment]
You need to update the command line to pass VER=v1.18 (or whatever) to make.

The default actually is to use a commit hash for the version on all builds to show that they are non-release. You might consider therefore that the current Docker behaviour is actually correct: Since official release binaries are not being generated.

**Comment by rjnorthrow** [comment]
Thank you :-)
