### ISSUE TITLE
Clockport issue

### ISSUE THREAD

**Issue by 8BitDreams** [keirf/amiga-stuff#69]
Hello,
 it's me, 8 Bit Dreams again...
I've stumbled on an issue with ATK V1.20 - it just hangs if started from IDE with Clockport device connected.. Same interrupt issue as it seems.. can this one be fixed somehow?🤔

**Comment by keirf** [comment]
Sorry for the very long delay!  It's not good news: It's impossible to mask the external interrupt independently of CIAB, and ATK tests CIAB interrupts so the line needs to be enabled. What's happening is an interrupt storm because the only thing that knows how to quench the interrupt stream from the Clockport device is that device's driver's interrupt service routine. And that's lost when we kill the OS.

This is one of the downsides of ATK taking over the system and not masking the CIAB/EXTER interrupt line.
